const CAPTIONS_AT_BASE = 1;
const CAPTIONS_AT_SPEAKER = 2;
const CAPTIONS_AT_BOTH = 3;
const CAPTION_CONDITION_4 = 4;

export default [
  [
    CAPTIONS_AT_BASE,
    CAPTIONS_AT_SPEAKER,
    CAPTIONS_AT_BOTH,
    CAPTION_CONDITION_4,
  ],
  [
    CAPTIONS_AT_SPEAKER,
    CAPTION_CONDITION_4,
    CAPTIONS_AT_BASE,
    CAPTIONS_AT_BOTH,
  ],
  [
    CAPTION_CONDITION_4,
    CAPTIONS_AT_BOTH,
    CAPTIONS_AT_SPEAKER,
    CAPTIONS_AT_BASE,
  ],
  [
    CAPTIONS_AT_BOTH,
    CAPTIONS_AT_BASE,
    CAPTION_CONDITION_4,
    CAPTIONS_AT_SPEAKER,
  ],
];
